-- Money columns are DECIMAL(19,2): exact, 2 fractional digits (minor units of EUR/USD/GBP).
-- Tax rates are DECIMAL(9,6), e.g. 0.070000 for 7 %.

-- ---------------------------------------------------------------------------
-- Transactions: one shared header row per transaction, whatever its type.
-- ---------------------------------------------------------------------------
CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(255)             NOT NULL,
    type        VARCHAR(16)              NOT NULL,
    currency    CHAR(3)                  NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total       DECIMAL(19, 2)           NOT NULL,
    version     BIGINT                   NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_transactions_external_id UNIQUE (external_id),
    CONSTRAINT ck_transactions_type CHECK (type IN ('flight', 'hotel', 'rail', 'navan_fee'))
);

-- Government / VAT-style taxes. Kept apart from fees on purpose.
CREATE TABLE transaction_tax_lines (
    transaction_id BIGINT         NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    line_no        INT            NOT NULL,
    name           VARCHAR(255)   NOT NULL,
    rate           DECIMAL(9, 6),
    amount         DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (transaction_id, line_no)
);

-- Carrier / merchant fees on the transaction (YQ surcharge, booking fee, ...).
CREATE TABLE transaction_fee_lines (
    transaction_id BIGINT         NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    line_no        INT            NOT NULL,
    name           VARCHAR(255)   NOT NULL,
    amount         DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (transaction_id, line_no)
);

-- ---------------------------------------------------------------------------
-- Type-specific details: one child table (or two) per transaction type.
-- ---------------------------------------------------------------------------
CREATE TABLE flight_details (
    transaction_id BIGINT         NOT NULL PRIMARY KEY REFERENCES transactions (id) ON DELETE CASCADE,
    origin         VARCHAR(64)    NOT NULL,
    destination    VARCHAR(64)    NOT NULL,
    fare           DECIMAL(19, 2) NOT NULL
);

CREATE TABLE flight_coupons (
    transaction_id BIGINT                   NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    line_no        INT                      NOT NULL,
    flight_number  VARCHAR(16)              NOT NULL,
    carrier        VARCHAR(8),
    from_location  VARCHAR(64)              NOT NULL,
    to_location    VARCHAR(64)              NOT NULL,
    departure_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (transaction_id, line_no)
);
CREATE INDEX ix_flight_coupons_flight_number ON flight_coupons (flight_number);

CREATE TABLE hotel_stays (
    transaction_id      BIGINT         NOT NULL PRIMARY KEY REFERENCES transactions (id) ON DELETE CASCADE,
    property_name       VARCHAR(255)   NOT NULL,
    street              VARCHAR(255)   NOT NULL,
    city                VARCHAR(128)   NOT NULL,
    postal_code         VARCHAR(32),
    country             VARCHAR(64)    NOT NULL,
    check_in            DATE           NOT NULL,
    check_out           DATE           NOT NULL,
    nights              INT            NOT NULL,
    room_rate_per_night DECIMAL(19, 2) NOT NULL
);

CREATE TABLE hotel_extras (
    transaction_id BIGINT         NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    line_no        INT            NOT NULL,
    name           VARCHAR(255)   NOT NULL,
    amount         DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (transaction_id, line_no)
);

CREATE TABLE rail_legs (
    transaction_id BIGINT                   NOT NULL REFERENCES transactions (id) ON DELETE CASCADE,
    line_no        INT                      NOT NULL,
    origin         VARCHAR(128)             NOT NULL,
    destination    VARCHAR(128)             NOT NULL,
    departure_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    arrival_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    train_number   VARCHAR(32),
    travel_class   VARCHAR(32),
    PRIMARY KEY (transaction_id, line_no)
);

CREATE TABLE navan_fees (
    transaction_id      BIGINT       NOT NULL PRIMARY KEY REFERENCES transactions (id) ON DELETE CASCADE,
    fee_kind            VARCHAR(32)  NOT NULL,
    description         VARCHAR(500),
    related_external_id VARCHAR(255),
    CONSTRAINT ck_navan_fees_kind CHECK (fee_kind IN ('trip_fee', 'agent_call_fee'))
);
CREATE INDEX ix_navan_fees_related_external_id ON navan_fees (related_external_id);

-- ---------------------------------------------------------------------------
-- Invoices: header + frozen per-transaction snapshot lines + rollups.
-- ---------------------------------------------------------------------------
CREATE TABLE invoices (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency    CHAR(3)                  NOT NULL,
    tax_total   DECIMAL(19, 2)           NOT NULL,
    fee_total   DECIMAL(19, 2)           NOT NULL,
    grand_total DECIMAL(19, 2)           NOT NULL,
    line_count  INT                      NOT NULL,
    version     BIGINT                   NOT NULL DEFAULT 0,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

-- snapshot = the full transaction (type, total, tax_lines, fee_lines, metadata) copied at invoicing time.
-- The FK has no ON DELETE: the database itself refuses to delete a transaction that is on an invoice.
CREATE TABLE invoice_lines (
    invoice_id     BIGINT         NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    line_no        INT            NOT NULL,
    transaction_id BIGINT         NOT NULL REFERENCES transactions (id),
    external_id    VARCHAR(255)   NOT NULL,
    type           VARCHAR(16)    NOT NULL,
    currency       CHAR(3)        NOT NULL,
    total          DECIMAL(19, 2) NOT NULL,
    snapshot       CLOB           NOT NULL,
    PRIMARY KEY (invoice_id, line_no),
    CONSTRAINT uq_invoice_lines_invoice_transaction UNIQUE (invoice_id, transaction_id)
);
-- "Is this transaction on any invoice?" -> index seek, used by PATCH/DELETE /transactions/{id}.
CREATE INDEX ix_invoice_lines_transaction_id ON invoice_lines (transaction_id);

CREATE TABLE invoice_tax_rollup (
    invoice_id BIGINT         NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    line_no    INT            NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    rate       DECIMAL(9, 6),
    amount     DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (invoice_id, line_no)
);

CREATE TABLE invoice_fee_rollup (
    invoice_id BIGINT         NOT NULL REFERENCES invoices (id) ON DELETE CASCADE,
    line_no    INT            NOT NULL,
    name       VARCHAR(255)   NOT NULL,
    amount     DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (invoice_id, line_no)
);
